export enum HEADER_KEY {
  CAPTCHA_TOKEN = 'X-Captcha-Token',
  LOG_ID = 'X-Trace-Id',
}

export enum ENV_KEY {
  JWT_EXPIRATION = 'JWT_EXPIRATION',
  JWT_SECRET = 'JWT_SECRET',
}

export enum ENTITY_STATUS {
  ACTIVE = 'active',
  SUSPENDED = 'suspended',
  INACTIVE = 'inactive',
}

export const ERR_CODE = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'.toLowerCase(),
  NOT_FOUND: 'NOT_FOUND'.toLowerCase(),
  INVALID_USERNAME_FORMAT: 'INVALID_USERNAME_FORMAT'.toLowerCase(),
  INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT'.toLowerCase(),
  INVALID_TX_HASH_FORMAT: 'INVALID_TX_HASH_FORMAT'.toLowerCase(),
  INVALID_PASSWORD_FORMAT: 'INVALID_PASSWORD_FORMAT'.toLowerCase(),
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS'.toLowerCase(),
  PASSWORD_INCORRECT: 'PASSWORD_INCORRECT'.toLowerCase(),
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS'.toLowerCase(),
  UNAUTHORIZED: 'UNAUTHORIZED'.toLowerCase(),
  USER_NOT_VERIFIED: 'USER_NOT_VERIFIED'.toLowerCase(),
  INVALID_TOKEN: 'INVALID_TOKEN'.toLowerCase(),
  USER_ALREADY_VERIFIED: 'USER_ALREADY_VERIFIED'.toLowerCase(),
  INVALID_CAPTCHA_TOKEN: 'INVALID_CAPTCHA_TOKEN'.toLowerCase(),
  OLD_PASSWORD_INCORRECT: 'OLD_PASSWORD_INCORRECT'.toLowerCase(),
  USER_NOT_FOUND: 'USER_NOT_FOUND'.toLowerCase(),
};
